/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50710
Source Host           : localhost:3306
Source Database       : mytest

Target Server Type    : MYSQL
Target Server Version : 50710
File Encoding         : 65001

Date: 2022-01-13 17:00:08
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for date
-- ----------------------------
DROP TABLE IF EXISTS `date`;
CREATE TABLE `date` (
  `type` varchar(255) DEFAULT NULL,
  `time` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of date
-- ----------------------------
INSERT INTO `date` VALUES ('跑步', '00:00:12', '2020-4-18', 'admin');
INSERT INTO `date` VALUES ('游泳', '00:00:12', '2020-4-18', 'admin');
INSERT INTO `date` VALUES ('打篮球', '00:00:06', '2020-4-18', '18637336376');
INSERT INTO `date` VALUES ('打羽毛球', '00:00:22', '2020-4-18', '18637336376');
INSERT INTO `date` VALUES ('撸铁', '00:00:06', '2020-4-18', '18312144255');
INSERT INTO `date` VALUES ('跑步', '00:00:06', '2020-4-18', '18637336376');
INSERT INTO `date` VALUES ('练瑜伽', '00:00:06', '2020-4-18', '18312144255');
INSERT INTO `date` VALUES ('踢足球', '00:00:05', '2020-4-19', '18312144255');
INSERT INTO `date` VALUES ('打兵乓球', '00:00:09', '2020-4-19', 'admin');
INSERT INTO `date` VALUES ('仰卧起坐', '00:00:09', '2020-4-19', 'admin');
INSERT INTO `date` VALUES ('俯卧撑', '00:00:09', '2020-4-19', '18312144255');
INSERT INTO `date` VALUES ('平板支撑', '00:00:06', '2020-4-19', '18312144255');
INSERT INTO `date` VALUES ('折返跑', '00:00:05', '2020-4-19', '18637336376');
INSERT INTO `date` VALUES ('跑步', '00:00:00', '2020-4-26', 'admin');
INSERT INTO `date` VALUES ('跑步', '00:00:05', '2020-4-26', '18637336376');

-- ----------------------------
-- Table structure for reliang
-- ----------------------------
DROP TABLE IF EXISTS `reliang`;
CREATE TABLE `reliang` (
  `classes` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `calory` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of reliang
-- ----------------------------
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 营养粉丝（香菇炖鸡味）', '热量：357 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 营养粉丝（牛肉味噌味）', '热量：363 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '白粥，又叫白粥（粳米），稀饭，大米粥，白米...', '热量：46 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 营养粉丝（番茄鸡蛋味）', '热量：348 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 低脂黑椒牛肉饭', '热量：169 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 法式南瓜汤', '热量：313 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 鸡肉松烤麦片', '热量：455 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 低脂咖喱鸡饭', '热量：179 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 低脂咖喱鸡饭', '热量：179 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 红枣黑米圈', '热量：392 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 抹茶红豆麦片', '热量：381 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 蛋白棒（英式红茶味）', '热量：424 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy S 意式阿拉棒', '热量：396 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 高蛋白微波蛋糕预拌粉（香...', '热量：389 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 红枣黑米圈（新包装）', '热量：392 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 鸡肉松烤麦片', '热量：455 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 山药紫薯圈', '热量：391 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '稀饭，又叫白粥（籼米），大米粥，白米粥', '热量：59 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '玉米（鲜），又叫苞谷、珍珠米、棒子、玉蜀黍...', '热量：112 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '燕麦片，又叫燕麦', '热量：338 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '面条（生），又叫面', '热量：301 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '面条（煮），又叫面', '热量：110 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '籼米粉，又叫米线、米粉、粉', '热量：356 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '面包', '热量：313 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '红薯，又叫地瓜、番薯、甘薯', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '小米粥', '热量：46 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '马铃薯，又叫土豆、洋芋、地蛋、山药蛋、洋番薯', '热量：81 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '包子（猪肉馅）', '热量：227 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '米饭，又叫大米饭，饭，蒸米、锅巴饭', '热量：116 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 高纤 奇亚籽苏打饼干', '热量：436 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '白薯，又叫山芋、红皮山芋，地瓜、甘薯', '热量：106 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '大米，又叫稻米、米、生米', '热量：346 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '全麦面包，又叫全麦面包、全麦吐司、全麦面包...', '热量：246 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '烙饼', '热量：259 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '花卷，又叫花之卷、大花卷、小花卷', '热量：214 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '油条，又叫小油条', '热量：388 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '曼可顿全麦高纤维面包', '热量：221 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '嘉顿 生命面包 450g', '热量：284 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '包子（三鲜馅）', '热量：223 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '馒头，又叫手工馒头、大馒头', '热量：223 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '油饼', '热量：403 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 低脂全麦面包', '热量：259 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 紫薯营养粥', '热量：319 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '单层汉堡（夹肉饼，加调料酱和蔬菜），又叫汉堡', '热量：256 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '紫薯，又叫甘薯（紫色）', '热量：106 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '米粉（干），又叫粉', '热量：349 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 鹰嘴豆', '热量：162 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 姜汁薄脆', '热量：446 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Ace 营养可可', '热量：356 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 奇亚籽豆乳味威化饼干', '热量：471 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 奇亚籽（新包装）', '热量：456 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 营养粉丝（酸辣汤味）', '热量：347 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 益生菌谷谷巧克力球', '热量：544 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fan 番茄牛肉轻火锅', '热量：93 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 可可低脂脆', '热量：388 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 奇亚籽豆乳味威化饼干（1小袋）', '热量：471 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 蛋白棒（英式红茶味）', '热量：390 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 蛋白棒（香浓可可味）', '热量：396 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', 'Easy Fun 榴莲果果麦片', '热量：441 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '黄油面包', '热量：331 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '方便面，又叫泡面', '热量：473 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '果料面包，又叫面包、水果面包', '热量：279 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '红豆，又叫赤小豆、红小豆、红饭豆、米赤豆、...', '热量：324 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '餐包，又叫小餐包、面包、豆沙小餐包', '热量：284 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '烧饼(加糖)', '热量：298 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '绿豆（干），又叫青小豆、植豆、交豆', '热量：329 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '薏米，又叫薏苡、薏苡仁、六谷米、苡米、薏仁...', '热量：361 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '粉丝（干），又叫细粉、线粉、丝粉、古称索粉', '热量：338 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '面条(标准粉，切面)', '热量：283 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦维面包', '热量：270 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '年糕（低糖桂花年糕），又叫蒙尔司 低糖年糕...', '热量：156 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦片', '热量：368 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '牛角面包，又叫面包', '热量：378 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '红烧牛肉方便面（面饼+调味料+蔬菜+肉酱）', '热量：447 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '双层奶酪汉堡（夹奶酪，双层肉饼、双层面包，...', '热量：285 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '山药，又叫薯蓣、山芋、诸薯、延草、薯药、大薯', '热量：57 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '炒饭，又叫炒米饭', '热量：188 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '芋头，又叫芋艿、毛芋', '热量：56 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '葡萄干面包，又叫面包', '热量：260 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '咸面包', '热量：275 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '黑芝麻汤圆，又叫元宵、汤圆、芝麻汤圆', '热量：311 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '黑米', '热量：341 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '芋头(煮)', '热量：60 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '多维面包', '热量：316 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '小麦粉(标准粉)，又叫面粉', '热量：362 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '澳洲燕麦片', '热量：359 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '玉米面(黄)', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '挂面', '热量：353 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '粉条（干）', '热量：338 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦当劳 汉堡包', '热量：262 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦当劳 吉士汉堡包', '热量：255 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '魔芋精粉', '热量：186 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦当劳 双层吉士汉堡', '热量：288 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '椰圈面包，又叫椰丝面包、面包', '热量：320 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '三明治（夹鸡蛋、干酪），又叫三明治', '热量：234 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '私房小厨苡仁粉', '热量：449 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦当劳 麦辣鸡腿汉堡，又叫鸡腿汉堡', '热量：320 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '奶香馒头', '热量：268 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '麦当劳 培根蔬萃双层牛堡', '热量：202 大卡(每100克)');
INSERT INTO `reliang` VALUES ('谷薯芋、杂豆、主食\n  ', '三明治（夹火腿、干酪）', '热量：244 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 高蛋白小酥鱼（藤椒味）', '热量：351 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋，又叫鸡子、鸡卵、蛋', '热量：144 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉肠（香辣味）', '热量：136 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 鸡胸肉丝（原味）', '热量：418 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉（黑椒味）', '热量：134 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉（香辣味）', '热量：130 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉丸（原味），又...', '热量：93 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy S 低脂牛肉小方（五香味）', '热量：165 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy S 低脂鸡蛋干（五香味）', '热量：124 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy S 低脂鸡胸肉（香辣味）', '热量：130 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 高蛋白小酥鱼（海苔味）', '热量：305 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy S 低脂鸡胸肉（黑椒味）', '热量：134 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉肠（原味）', '热量：131 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪小排，又叫排骨、猪排', '热量：278 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡（土鸡，家养)', '热量：124 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡（母鸡，一年内）', '热量：256 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡（肉鸡，肥）', '热量：389 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸭肉，又叫鸭子、鹜肉、家凫肉', '热量：240 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪蹄，又叫猪脚、猪手、猪蹄爪', '热量：260 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '螃蟹（河蟹），又叫螃蟹、毛蟹、稻蟹、中华绒...', '热量：103 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉（瘦），又叫猪精肉，瘦肉', '热量：143 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋（煮），又叫水煮蛋，水煮鸡蛋，白煮蛋，...', '热量：151 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋白（鸡蛋清），又叫鸡蛋白、鸡蛋清、蛋清、蛋白', '热量：60 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '火腿肠', '热量：212 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡胸脯肉，又叫鸡柳肉、鸡里脊肉、鸡胸、鸡胸肉', '热量：133 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '牛肉（牛腩），又叫腹部肉', '热量：332 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '荷包蛋（油煎），又叫荷包蛋、煎蛋、煎荷包蛋...', '热量：195 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '咸鸭蛋，又叫盐蛋、腌蛋、味蛋', '热量：190 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉(肥瘦)，又叫豕肉、彘肉', '热量：395 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '瓦罐鸡汤（含料），又叫瓦罐汤', '热量：190 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '瓦罐鸡汤（无料）', '热量：27 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪小排（良杂猪）', '热量：351 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '松花蛋(鸡蛋)，又叫皮蛋、变蛋、彩蛋、碱蛋、泥蛋', '热量：178 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉(奶脯)，又叫软五花、奶脯、五花肉', '热量：349 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪大排，又叫猪排', '热量：264 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '牛肉(肥瘦)，又叫肥牛', '热量：125 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '牛肉(里脊)，又叫牛里脊', '热量：107 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉肠', '热量：142 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '松花蛋(鸭蛋)，又叫皮蛋', '热量：171 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡蛋干（五香味）', '热量：145 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡蛋干（山椒味）', '热量：125 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂蛋清鸡肉饼（原味）', '热量：139 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', 'Easy Fun 低脂鸡胸肉肠（黑椒味）', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '草鱼，又叫鲩鱼、混子、草鲩、草包鱼、草根鱼...', '热量：113 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋(土鸡)', '热量：138 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋（白皮）', '热量：138 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋(红皮)', '热量：156 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡腿，又叫鸡腿肉', '热量：181 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '酱牛肉', '热量：246 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鱼丸，又叫鱼丸子、鱼丸鱼蛋', '热量：107 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '香肠，又叫腊肠、南肠、灌肠', '热量：508 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '牛肉（瘦）', '热量：106 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '肯德基 吮指原味鸡，又叫KFC 吮指原味鸡', '热量：346 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鲫鱼，又叫河鲫、鲋鱼、喜头、鲫瓜子、喜头鱼...', '热量：108 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '火腿，又叫兰熏、熏蹄、南腿', '热量：330 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '牛肉干，又叫牛干巴', '热量：550 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '咸鸭蛋（煮）', '热量：177 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡翅，又叫鸡翼、大转弯', '热量：194 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '烤鸡，又叫吊烧鸡', '热量：240 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '热狗肠', '热量：307 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鹌鹑蛋，又叫鹑鸟蛋、鹌鹑卵', '热量：160 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鲤鱼，又叫龙门鱼、鲤拐子、赤鲤、黄鲤、白鲤、赖鲤', '热量：109 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '明虾', '热量：85 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '北京烤鸭', '热量：436 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鱼片干', '热量：303 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡爪，又叫鸡掌、凤爪、鸡脚、凤足', '热量：254 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸡蛋黄，又叫蛋黄', '热量：328 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '无油煎蛋，又叫煎蛋', '热量：164 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '叉烧肉', '热量：279 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '广东香肠', '热量：433 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '肯德基 新奥尔良烤翅，又叫KFC 新奥尔良烤翅', '热量：240 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '黄鱼(小黄花鱼)，又叫小黄花鱼、黄花鱼、花...', '热量：99 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '青鱼，又叫青皮鱼、青鳞鱼、青混、鲭、黑鲩、螺狮青', '热量：118 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸭蛋，又叫鸭卵', '热量：180 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉松，又叫肉松', '热量：396 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉(里脊)，又叫梅肉、里脊肉', '热量：155 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '麦当劳 麦香鱼', '热量：253 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪血，又叫液体肉、血豆腐、血花', '热量：55 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪蹄(熟)', '热量：260 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '虾仁（红）', '热量：48 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肉(肋条肉)', '热量：568 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '虾皮', '热量：153 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '羊肉串(烤)', '热量：206 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '基围虾，又叫南美虾', '热量：101 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '猪肝', '热量：129 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸭胸脯肉', '热量：90 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '虾虎，又叫虾虎、琵琶虾、虾蛄、虾爬子', '热量：81 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '羊肉(肥瘦)，又叫山羊肉、绵羊肉、羊腰窝肉、羊腩', '热量：203 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '墨鱼丸', '热量：128 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鱿鱼(水浸)', '热量：75 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '黄鱼(大黄花鱼)，又叫大黄花鱼、黄鱼、大鲜...', '热量：97 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '带鱼，又叫刀鱼、裙带鱼、牙带、白带鱼、柳鞭...', '热量：127 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '脆皮肠', '热量：302 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '酱鸭，又叫鸭肉', '热量：266 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '河虾', '热量：87 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '鸭翅，又叫鸭肉、老卤鸭翅', '热量：146 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '培根（熏肉）', '热量：181 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '麦当劳 麦乐鸡，又叫麦乐鸡', '热量：281 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '虾米，又叫海米、金钩、开洋', '热量：198 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蛋类、肉类及制品\n  ', '麦当劳 香骨鸡腿', '热量：217 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶', '热量：72 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂牛奶，又叫纯牛奶，牛乳', '热量：54 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '拿铁（全脂，无糖），又叫拿铁咖啡', '热量：44 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '奶酪，又叫乳酪、芝士、起司、计司', '热量：328 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶（中脂）', '热量：64 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '脱脂酸奶', '热量：57 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '脱脂奶粉', '热量：356 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶（调味）', '热量：88 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶(果料)，又叫果料酸奶', '热量：67 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶（果粒），又叫果粒酸奶', '热量：97 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 高钙牛奶，又叫蒙牛袋装高钙牛奶', '热量：59 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '脱脂牛奶，又叫脱脂奶', '热量：33 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 e+益生菌酸牛奶（原味）220ml ...', '热量：45 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '低脂牛奶，又叫低脂奶 脱脂奶', '热量：43 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '早餐奶', '热量：68 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '酸奶（高蛋白）', '热量：62 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '奶片', '热量：472 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂牛奶粉', '热量：478 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 纯牛奶，又叫光明牛奶', '热量：66 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 优倍 高品质鲜牛奶，又叫光明 优倍高...', '热量：65 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 优倍 0脂肪 高品质脱脂鲜牛奶', '热量：35 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 优倍 0乳糖 巴士杀菌调制乳', '热量：67 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 致优 全鲜乳，又叫光明 致优全鲜乳', '热量：63 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 0脂肪 鲜牛奶，又叫光明 0脂肪鲜牛奶', '热量：32 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶(强化VA，VD)，又叫牛乳(强化VA...', '热量：51 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 低脂牛奶', '热量：43 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 木糖醇酸牛奶，又叫蒙牛木糖醇酸奶', '热量：63 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '低脂奶酪', '热量：241 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 无蔗糖酸牛奶（利乐包）150g', '热量：52 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 酸牛奶（草莓+树莓）100g （小盒装）', '热量：92 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明减脂90%脱脂鲜牛奶', '热量：32 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利优品嘉人优酪乳（原味）', '热量：73 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明畅优红枣燕麦低脂酸奶', '热量：69 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 芦荟酸奶', '热量：87 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利酸牛奶(原味)', '热量：87 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂速溶奶粉', '热量：466 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '雀巢 高钙高铁奶粉，又叫Nestle 高钙...', '热量：416 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 大果粒酸牛奶（红茶+草莓+椰果）', '热量：92 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '奶酪（光明牌）', '热量：348 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 优品嘉人优酪乳酸牛奶', '热量：78 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明优＋高品质牛奶(利乐枕）', '热量：62 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（完达山牌），又叫牛乳（完达山牌）', '热量：60 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 冠益乳特品酸牛奶（原味），又叫蒙牛冠...', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂加糖奶粉', '热量：490 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 酸牛奶（草莓味）罐装950ml（盒装）', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '雀巢 高纤高钙奶粉，又叫雀巢/Nestle...', '热量：428 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '味全优酪乳（原味）', '热量：88 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛冠益乳特品酸牛奶木糖醇味', '热量：63 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利优品嘉人优酪乳·酸牛奶[焕颜蓝莓]', '热量：78 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '低脂奶粉', '热量：423 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 畅轻酸奶（黄桃果粒）瓶装580g', '热量：103 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 酸牛奶（原味） ', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '奶粉(多维奶粉)，又叫奶粉', '热量：484 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（巧克力味，卡夫 牌），又叫牛奶（巧克...', '热量：80 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '法国百吉福 低脂芝士片，又叫法国百吉福低脂芝士片', '热量：195 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '君乐宝 东方知味红枣酸牛奶', '热量：61 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 畅轻酸奶（草莓果粒）瓶装580g', '热量：103 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（巧克力味，三元牌）', '热量：74 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂甜炼乳（雀巢 ），又叫全脂甜炼乳（Ne...', '热量：380 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明无蔗糖酸奶（桶装）', '热量：60 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '奶酪（骑士牌）', '热量：386 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明畅优优酪乳酸牛奶原味，又叫光明 畅优 ...', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '羊奶，又叫鲜羊奶', '热量：59 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 大果粒酸牛奶（绿茶+蒟蒻+椰果） 大...', '热量：92 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明减脂90%鲜牛奶', '热量：32 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '君乐宝高钙无蔗糖酸牛奶', '热量：45 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '学生奶', '热量：66 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '银桥 益生菌酸牛奶（原味）', '热量：78 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利ABLS益生菌酸牛奶－无蔗糖', '热量：54 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 畅优B+100活性益生菌果粒酸牛奶（青提）', '热量：69 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利妙芝新鲜奶酪', '热量：118 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 纯牛奶香浓3.5', '热量：62 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（草莓味，卡夫 牌），又叫牛奶（草莓味...', '热量：79 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '高钙高铁奶粉（可淇牌）', '热量：437 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 缔芝特低脂早餐奶酪', '热量：215 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '雀巢 全脂甜奶粉，又叫Nestle 全脂甜奶粉', '热量：462 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（乐百氏牌），又叫牛乳（乐百氏牌）', '热量：67 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 早餐奶酪（高钙）', '热量：263 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '味全 优酪乳酸牛奶健康粗粮（蓝莓口味）', '热量：84 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '卡士 鲜酪乳调味酸牛乳（原味）', '热量：82 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 健能草莓果粒酸牛奶 100g', '热量：87 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 红枣酸奶', '热量：92 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 酸牛奶（原味）', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 益生菌酸牛奶', '热量：98 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '蒙牛 冠益乳冠菌优酪乳酸牛奶（原味）瓶装560g', '热量：85 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明 90%低脂鲜牛奶', '热量：18 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利 早餐奶酪（原味）', '热量：287 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明汉方草本酸牛奶', '热量：91 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '达能 原味酸牛奶，又叫Danone 原味酸牛奶', '热量：58 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '婴儿奶粉', '热量：443 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '卡士 鲜酪乳 果味酸牛乳（粟米）', '热量：73 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '全脂奶粉（伊利牌）', '热量：504 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '纽麦福 低脂高钙奶，又叫 Meadow F...', '热量：61 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '小小光明健康成长奶酪', '热量：190 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '雀巢 全仕奶（巧克力味），又叫Nestle...', '热量：72 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', 'Dr.Oetker Onken脱脂酸奶', '热量：48 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '光明奶酪经典黄波芝士片', '热量：280 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '达能 TAILLEFINE脱脂酸奶，又叫D...', '热量：42 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '伊利高钙奶酪', '热量：287 大卡(每100克)');
INSERT INTO `reliang` VALUES ('奶类及制品\n  ', '牛奶（强化锌、钙），又叫牛乳（强化锌、钙）', '热量：60 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '苹果，又叫滔婆、柰、柰子、频婆、平波、天然子', '热量：53 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '大白菜，又叫白菜', '热量：20 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '小白菜，又叫青菜、油白菜、白菜秧、白菜、杭白菜', '热量：17 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '香蕉，又叫蕉子、蕉果、甘蕉', '热量：93 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '番茄，又叫西红柿、洋柿子、狼桃、番李子、金...', '热量：15 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '黄瓜，又叫青瓜', '热量：16 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', 'Easy Fun 低脂魔芋爽（山椒味）', '热量：49 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', 'Easy Fun 低脂魔芋爽（香辣味）', '热量：49 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', 'Easy Ace 多吃蔬菜', '热量：244 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '西瓜，又叫寒瓜、天生白虎汤、夏瓜、水瓜', '热量：31 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '桃子，又叫桃', '热量：42 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '上海青，又叫青菜，小青菜、青菜', '热量：18 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '红富士苹果', '热量：49 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '橙，又叫橙子、金球、香橙、黄橙、脐橙', '热量：48 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '菜心，又叫白菜薹、薹菜', '热量：28 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '西兰花，又叫绿菜花、西蓝花', '热量：36 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '柚子，又叫文旦、香抛、霜柚、臭橙、柚', '热量：42 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '白萝卜，又叫萝卜、莱菔', '热量：16 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '梨，又叫梨子、快果、玉乳、果宗、蜜父、雪梨...', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '花菜，又叫菜花、花椰菜、椰花菜、洋花菜、鲜花菜', '热量：20 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '结球甘蓝(紫），又叫紫甘蓝、甘蓝', '热量：25 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '冬枣，又叫枣子，枣', '热量：113 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '猕猴桃，又叫毛桃、藤梨、苌楚、羊桃、毛梨、...', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '南瓜，又叫麦瓜、番瓜、倭瓜、金瓜、伏瓜、饭...', '热量：23 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '胡萝卜（老），又叫萝卜、黄萝卜、丁香萝卜、...', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '生菜，又叫牛俐、鲜生菜、鲜圆生菜', '热量：16 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '橘子，又叫橘柑、柑橘、桔柑子', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '木瓜，又叫乳瓜、木梨、文冠果', '热量：30 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '葡萄，又叫草龙珠、山葫芦、蒲桃、菩提子、', '热量：45 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '圣女果，又叫葡萄番茄、小西红柿、小番茄', '热量：25 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '冬瓜，又叫白瓜、水芝、地芝、枕瓜、濮瓜、白...', '热量：12 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '胡萝卜（嫩），又叫萝卜、胡萝菔、黄萝卜、金...', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '卷心菜（包菜，圆白菜），又叫圆白菜，包菜，甘蓝', '热量：24 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '红枣(鲜)，又叫红枣、美枣、良枣', '热量：125 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '红枣，又叫红枣、大枣、枣子', '热量：276 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '竹笋（鲜），又叫笋、毛笋、竹芽、竹萌', '热量：23 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '荸荠，又叫马蹄', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '木耳(水发)，又叫黑木耳、云耳', '热量：27 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '柑桔，又叫桔子', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '菠菜，又叫菠棱菜、赤根菜、波斯草、鹦鹉菜、...', '热量：28 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '菠萝，又叫番梨、露兜子、凤梨', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '火龙果，又叫仙蜜果、红龙果', '热量：55 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '草莓，又叫大草莓、士多啤梨、红莓、地莓', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '芒果，又叫庵罗果、檬果、蜜望子、香盖', '热量：35 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '豆芽（绿豆芽），又叫巧芽、豆芽菜、如意菜、...', '热量：16 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '香菇（鲜），又叫冬菇、香菌、爪菰、花菇、香...', '热量：26 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '茄子，又叫落苏、茄瓜', '热量：23 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '哈密瓜，又叫甜瓜', '热量：34 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '甜瓜，又叫甘瓜、库洪（维吾尔语）', '热量：26 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '李子，又叫布朗、脆李、金沙李、嘉庆子、李实...', '热量：38 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '海带（浸），又叫江白菜，昆布', '热量：16 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '芹菜（药芹），又叫旱芹、样芹菜、药芹、香芹...', '热量：13 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '通心菜（空心菜），又叫蕹菜', '热量：23 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '葡萄柚（西柚），又叫红柚、红心柚', '热量：33 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '鱼腥草（叶），又叫折耳根', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '木耳(干)，又叫黑木耳、云耳、桑耳、松耳', '热量：265 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '豌豆苗，又叫豆苗', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '小葱，又叫香葱、绵葱、火葱、葱', '热量：27 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', 'Easy Fun 土耳其杏干', '热量：268 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '葡萄干', '热量：344 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '青椒，又叫青辣椒、尖椒、海椒', '热量：22 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '洋葱，又叫洋葱头、玉葱、葱头、圆葱、球葱、洋葱', '热量：40 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '金针菇，又叫朴菰 、构菌、冻菌、金菇、毛柄...', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '莲藕，又叫藕', '热量：47 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '红提子葡萄，又叫提子、红提', '热量：54 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '海带（鲜），又叫昆布、江白菜、纶布、海昆布...', '热量：13 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '荔枝，又叫丹荔、丽枝、香果、勒荔、离支', '热量：71 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '生菜(叶用莴苣)', '热量：12 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '结球甘蓝（绿），又叫甘蓝、卷心菜、包心菜、...', '热量：26 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '樱桃，又叫车厘子、莺桃、含桃、荆桃、朱樱、...', '热量：46 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '豆芽（黄豆芽），又叫大豆芽、清水豆芽、黄豆芽', '热量：47 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '苦瓜，又叫凉瓜、癞瓜、锦荔枝、癞葡萄', '热量：22 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '小叶桔', '热量：40 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '豆角', '热量：34 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '芹菜茎', '热量：22 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '鹅黄梨', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '丝瓜，又叫天丝瓜、天罗、蜜瓜、布瓜、天吊瓜...', '热量：20 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '巨峰葡萄', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '白兰瓜，又叫兰州瓜、华莱士、兰州蜜瓜', '热量：23 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '马奶子葡萄', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '桑葚，又叫桑椹', '热量：57 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '紫菜(干)，又叫索菜、子菜、甘紫菜', '热量：250 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '国光苹果', '热量：56 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '四季豆，又叫菜豆、豆角、云扁豆、龙爪豆、龙...', '热量：31 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '莴笋，又叫莴苣、春菜、生笋、千金菜、茎用莴...', '热量：15 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '蘑菇(鲜蘑)，又叫蕈、菌、茸、蘑菰、蘑菇蕈...', '热量：24 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '长把梨', '热量：62 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '银耳(干)，又叫白木耳、雪耳', '热量：261 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '枣（干，大)', '热量：317 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '杏，又叫杏果、甜梅、叭达杏、杏实、杏子', '热量：38 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '杨梅，又叫龙睛、朱红、水杨梅、白蒂梅、树梅', '热量：30 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '山楂（红果），又叫山果红、红果、胭脂果、海...', '热量：102 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '桑葚（红），又叫桑椹', '热量：55 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '芹菜（水芹），又叫水芹菜、刀芹、蜀芹、野芹菜', '热量：13 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '韭菜，又叫壮阳草、赶阳草、长生草、起阳草', '热量：25 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '紫葡萄', '热量：45 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '西瓜(京欣一号)', '热量：34 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '李子杏', '热量：37 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '西葫芦，又叫搅瓜、白南瓜', '热量：19 大卡(每100克)');
INSERT INTO `reliang` VALUES ('蔬果和菌藻\n  ', '黄香蕉苹果', '热量：53 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆浆', '热量：31 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '瓜子，又叫向日葵子、天葵子、葵子、瓜子仁、瓜子', '热量：615 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆浆（甜）', '热量：34 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干（白干），又叫豆干、白干', '热量：197 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '黑芝麻，又叫芝麻籽(黑)、胡麻、巨胜', '热量：559 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐，又叫水豆腐', '热量：84 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '核桃（干），又叫核桃仁、山核桃、胡桃仁、羌...', '热量：646 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐花，又叫豆腐花、豆花', '热量：15 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐(南)，又叫嫩豆腐、软豆腐', '热量：87 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '炒花生', '热量：601 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生米（生），又叫花生仁（生）', '热量：574 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生米（炒），又叫花生仁（炒）', '热量：589 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐(北)，又叫软玉', '热量：116 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '栗子，又叫板栗', '热量：214 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', 'Easy Fun 低脂夹心牛肉豆脯（五香味）', '热量：121 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐皮（干），又叫百片、腐衣、豆皮、油皮', '热量：447 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', 'Easy Fun 高纤麦芽豆乳', '热量：365 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆奶粉', '热量：423 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆奶', '热量：30 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(烤干，加盐)', '热量：617 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐脑(带卤)，又叫豆腐花、豆腐脑', '热量：48 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生（鲜），又叫落花参、番豆、长生果、落地...', '热量：313 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁，又叫南杏仁', '热量：578 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '核桃(鲜)', '热量：336 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '黄豆，又叫大豆、黄大豆、枝豆、菜用大豆', '热量：390 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '毛豆，又叫枝豆、菜用大豆', '热量：131 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(香干)，又叫豆干、香干', '热量：152 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '葵花子（奶油香瓜子）', '热量：620 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '油豆腐', '热量：245 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆浆粉', '热量：426 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '内酯豆腐，又叫豆腐', '热量：50 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(大)', '热量：540 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '山核桃（熟），又叫小核桃', '热量：658 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生（烤、密日兴牌）', '热量：475 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '开心果', '热量：631 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '素鸡', '热量：194 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '黑豆，又叫黑大豆、乌豆、橹豆、马料豆、料豆...', '热量：401 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(卤干)，又叫豆干', '热量：339 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '腰果（熟）', '热量：615 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '西瓜子(炒)', '热量：582 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '腐竹（干），又叫支竹、甜竹、腐筋', '热量：461 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生米（油炸），又叫花生仁（油炸）', '热量：583 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐丝', '热量：203 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '千张，又叫百页、皮子、豆片、干豆腐', '热量：262 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '花生（烤、勤俭牌）', '热量：586 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '青豆（干），又叫青大豆', '热量：398 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(酱油干)，又叫豆干', '热量：157 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '腰果，又叫鸡腰果、介寿果', '热量：559 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '莲子(干)，又叫莲宝、莲米、藕实、水芝、丹...', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '山核桃', '热量：616 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '黑芝麻糊粉', '热量：408 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(小香干)，又叫豆干', '热量：174 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(原味)，又叫北杏仁、杏核仁、杏子、杏人', '热量：596 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '栗子(鲜)，又叫板栗、大栗、栗果、毛栗、棋...', '热量：188 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '葵花子(炒)', '热量：625 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '南瓜子(炒)，又叫南瓜籽、白瓜子', '热量：582 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(菜干)，又叫豆干', '热量：137 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '乐购 浓豆浆，又叫TESCO 浓豆浆', '热量：26 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '西瓜子(话梅)', '热量：567 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '黄豆粉，又叫大豆粉', '热量：432 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐卷', '热量：203 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', 'O\'Day 扯扯素肉（麻辣味）', '热量：148 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', 'Easy Fun 奇亚籽', '热量：428 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '西瓜子（熟），又叫黑瓜子', '热量：550 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(炒)', '热量：618 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(烤干，不加盐)', '热量：617 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐丝(油)', '热量：304 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '白果(干)，又叫银杏', '热量：355 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '洽洽香瓜子', '热量：616 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '南瓜子仁，又叫白瓜子、南瓜仁', '热量：576 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '榛子，又叫尖栗、平榛、山反栗', '热量：561 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '白芝麻，又叫芝麻籽(白)', '热量：536 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(熏干)，又叫豆干', '热量：154 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '素火腿', '热量：213 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '美国大杏仁', '热量：586 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁（熟、带壳）', '热量：648 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '毛核桃', '热量：184 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '榛子仁（熟）', '热量：628 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '松子(炒)，又叫罗松子、海松子、新罗松子、...', '热量：644 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '榛子(炒)', '热量：611 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁（熟、去壳）', '热量：625 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '旭松纳豆', '热量：190 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '栗子(河北迁西），又叫板栗（河北迁西）', '热量：182 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(蒲包干)', '热量：135 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '桃仁，又叫毛桃仁、扁桃仁、大桃仁、光桃仁、炒桃仁', '热量：429 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '松子仁，又叫海松子、新罗松子', '热量：718 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐干(臭干)', '热量：99 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(过油炸干)', '热量：631 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆腐丝(干)', '热量：451 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '榛子（熟）', '热量：642 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '白玉 家庭号无糖豆浆', '热量：23 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '葵花子（熟）', '热量：591 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '香榧（熟），又叫香榧、赤果、野极子、榧实、...', '热量：644 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '芡实米（干），又叫鸡头米、水鸡头、鸡头苞、...', '热量：352 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '杏仁(漂白后)', '热量：602 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '松子', '热量：553 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '栗子（山东），又叫板栗（山东）', '热量：168 大卡(每100克)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '豆奶粉（多力牌）', '热量：405 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '南方 无糖黑芝麻糊', '热量：416 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('坚果、大豆及制品\n  ', '西瓜子仁', '热量：566 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Ace 绿咖啡果蔬饮', '热量：76 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 冷萃冻干速溶咖啡粉', '热量：337 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 法式南瓜汤', '热量：313 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Ace 益生菌代餐奶昔（酸奶味）', '热量：379 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Ace 茶多酚代餐奶昔（奶茶味）', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy S 香草味代餐饮', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy S 玉米蔬菜味代餐饮', '热量：384 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '饮用水，又叫水、自来水、白开水', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '咖啡粉，又叫速溶咖啡粉', '热量：218 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '麦斯威尔 原味咖啡，又叫  maxwell...', '热量：478 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '黑咖啡（液），又叫美式、美式咖啡、澳黑、咖...', '热量：1 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '矿泉水，又叫水', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '啤酒', '热量：32 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '珍珠奶茶，又叫奶茶、招牌奶茶', '热量：52 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '天福茗茶 绿茶粉', '热量：328 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '绿茶（茶叶本身），又叫绿茶、茶叶', '热量：328 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '柠檬汁', '热量：27 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '江米酒，又叫糯米酒、甜酒、酒酿、醪糟', '热量：91 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '红酒', '热量：96 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '茶水，又叫茶', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '橙汁饮料（汇源牌）', '热量：46 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '光明 藜麦谷物牛奶', '热量：76 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '光明 巧克努力 巧克力牛奶饮品', '热量：87 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '光明 一只椰子 牛乳饮品', '热量：58 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 汽水，又叫可乐', '热量：43 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '康宝莱 蛋白混合饮料（巧克力味）', '热量：370 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '私房小厨杏仁粉', '热量：580 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '甘蔗汁', '热量：65 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '铁观音茶（茶叶本身）', '热量：334 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可可粉', '热量：349 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '农夫山泉 水溶C100 柠檬汁，又叫农夫水...', '热量：38 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '红葡萄酒', '热量：74 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '红茶（茶叶本身）', '热量：324 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '统一弗蕾奶茶-经典麦香', '热量：33 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '雀巢 原叶低糖绿茶，又叫Nestle 原叶...', '热量：16 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '正宗椰树牌 椰树牌 椰汁', '热量：50 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 零度 汽水，又叫0度可乐', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 樱桃味汽水', '热量：32 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 姜味汽水', '热量：31 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 健怡 汽水', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐 纤维+ 汽水', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '杏仁露', '热量：46 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可口可乐  香草味汽水', '热量：43 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '弗蕾绿奶茶（鲜绿茉香口味）', '热量：33 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '可乐，又叫可乐', '热量：45 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 综合营养素（树莓味）', '热量：49 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 营养玄米饮（抹茶味）', '热量：358 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 营养可可', '热量：366 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 路易波士茶', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 纯马黛茶', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 营养饮（玉米蔬菜味）', '热量：366 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 玉米须茶', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Beauty Reset 焕白肌密果味饮料', '热量：29 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '芬达 橙味汽水', '热量：34 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'Easy Fun 意式咖啡包（奶萃）', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'O\'day 运动蛋白粉（蜜桃味）', '热量：404 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 畅爽西梅饮', '热量：132 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 咖啡蛋白饮', '热量：417 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模25 果蔬营养素（番茄味）', '热量：70 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '喜乐(乳酸饮料)', '热量：53 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '橙汁汽水，又叫橙汁', '热量：20 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', 'CoCo都可 鲜芋青稞奶茶-不加糖（营养师...', '热量：102 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '咖啡豆', '热量：313 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '十全苹果醋', '热量：29 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '维他 奶原味豆奶饮料（低脂肪），又叫Vit...', '热量：48 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '七喜', '热量：30 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '橙汁饮料（光明牌）', '热量：44 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '康师傅 绿茶（低糖）', '热量：15 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '麦氏典藏MAXIM原味咖啡', '热量：441 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '雀巢 冰爽茶冰极柠檬味绿茶饮料，又叫Nes...', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '麦斯威尔 致醇口味咖啡，又叫  maxwe...', '热量：365 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '丹特 牌蜂蜜柚子茶，又叫DAMTUH 牌蜂...', '热量：260 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '橘子汁', '热量：119 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '椰子汁饮料', '热量：51 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '康师傅 茉莉清茶（淡雅低糖）', '热量：16 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '统一  绿茶（低糖茉莉花味）', '热量：16 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '三得利 乌龙茶（无糖），又叫SUNTORY...', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '康师傅 茉莉蜜茶', '热量：31 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '花茶（花茶本身），又叫香片、熏花茶、窨花茶', '热量：316 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '胡萝卜汁饮料', '热量：24 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '苹果汁饮料（光明牌）', '热量：54 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '红果汁', '热量：157 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '惠尔康谷粒谷力玉米南瓜浓浆', '热量：44 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '自制蜂蜜柚子茶', '热量：137 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '超模17 营养奶昔', '热量：359 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '葡萄酒（干红，12%，张裕牌）', '热量：75 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '蒙牛果蔬酸酸乳', '热量：31 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '汇源橙汁饮料', '热量：36 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '巧克力豆奶', '热量：39 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '大麦茶（茶叶本身）', '热量：393 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '农夫茶龙井绿茶饮品-低糖', '热量：19 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '味佳牌蜂蜜柚子茶', '热量：250 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '惠尔康 谷粒谷力燕麦浓浆', '热量：58 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '柠檬茶（雀巢 牌，固体饮料），又叫柠檬茶（...', '热量：406 大卡(每100克)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '汇源100%苹果汁', '热量：38 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '美汁源 果粒橙', '热量：41 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', ' 惠尔康谷粒谷力荞麦浓浆', '热量：18 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '酸乳饮料', '热量：54 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '麒麟午后红茶奶茶饮料-低脂肪', '热量：34 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('饮料\n  ', '葡萄酒（干红，11.5%，长城牌）', '热量：72 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '色拉油', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '花生油，又叫落花生油、果油、油、食用油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '豆油，又叫油，食用油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '混合油(菜+棕)', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '葵花籽油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '橄榄油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '菜籽油，又叫菜子油、菜油、油菜籽油、芸苔油...', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '辣椒油，又叫红油、油辣子', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '芝麻油，又叫麻油、芝麻油', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '金龙鱼食用调和油', '热量：884 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '猪油(板油)，又叫油，食用油，猪网油', '热量：827 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '玉米油', '热量：895 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '猪油(炼)，又叫大油、荤油、猪脂膏', '热量：897 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '香油', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '黄油，又叫白脱油', '热量：888 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '欧丽薇兰特级初榨橄榄油', '热量：814 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '金龙鱼 玉米油', '热量：884 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '胡麻油，又叫亚麻油、亚麻子油、胡麻子油', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '粟米油，又叫玉米胚芽油', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '茶油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '大麻油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '佳之选 橄榄油', '热量：823 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '金牛 芝麻油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '坎诺拉健康黄油', '热量：700 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'olivoila 初榨橄榄油', '热量：884 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '牛油，又叫牛脂', '热量：835 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '融氏纯玉米油', '热量：860 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '安佳 淡奶油，又叫Anchor 淡奶油', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '黄油渣', '热量：599 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '牛油(炼)', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '光明植物黄油', '热量：719 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '雀巢 三花全脂淡奶，又叫Nestle 三花...', '热量：141 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '棕榈油', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '麦芽油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '油茶籽油', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '（AGIA）阿茜娅纯橄榄油', '热量：878 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Somerfield 纯菜油', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '羊油，又叫羊脂', '热量：824 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '棉籽油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '白脱(食品工业)，又叫牛油，黄油', '热量：744 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '珠江 桥牌小磨芝麻油', '热量：900 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '鸭油(炼)', '热量：897 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '核桃油', '热量：895 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '椰子油', '热量：898 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '统一纯橄榄油', '热量：818 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '酥油', '热量：860 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'HOMEBRAND鲜奶油', '热量：331 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Allowuie zero黄油', '热量：733 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Land Lakes油菜籽植物黄油', '热量：714 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '米糠油', '热量：894 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '卡拉利特级橄榄油', '热量：822 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '羊油(炼)', '热量：895 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '常春 淡奶油（麻辣味）', '热量：350 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'PAMS超淡橄榄油', '热量：810 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '阿尔法 辣米油', '热量：844 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '红花油', '热量：899 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '天然世家 野生铁核桃油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '福临门 天天五谷食用调和油，又叫福临门 天...', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Lactima 牛油（无盐）', '热量：740 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '长生 特级初榨橄榄油', '热量：877 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '明治 高纤黄油，又叫Meiji 高纤黄油', '热量：265 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '百尚 淡黄油块，又叫Payson Bret...', '热量：731 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Cocoyummy 有机农椰子油', '热量：802 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Sparta Tree 黄金树亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '优飨 纯正亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '珏士高 初榨椰子油，又叫jax coco ...', '热量：820 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Mabarajab\'s Choice 酥油', '热量：884 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '蒙草香 亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '纵宝 蟹黄油', '热量：406 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '马赛罗 特级初榨橄榄油', '热量：807 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '五丰 花椒油', '热量：805 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '保生堂 亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '安佳 黄油（有盐），又叫Anchor 黄油...', '热量：733 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '梅赛德斯 特级初榨橄榄油', '热量：810 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '福来康泰 亚麻籽玉米食用调和油', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Terra Creta/克里特之光 特级初...', '热量：814 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '福临门 纯香大豆油（非转基因）', '热量：883 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '蜀九香 芝麻调和油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '拉杜蓝乔 压榨亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '西王智利多 有机亚麻籽油', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '长白工坊 有机婴幼儿装亚麻籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Balade 低脂黄油', '热量：386 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Lucerne  鲜奶油', '热量：300 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '金龙鱼 纯香大豆油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '柯可兰 特级冷压初榨橄榄油，又叫Kirkl...', '热量：824 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '福来康泰 紫苏籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Gold\'n Canola Ω-3油', '热量：813 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '爱度 六度提纯亚麻籽油', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '香必居 鲜花椒油', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '长白工坊 有机南瓜籽油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '蓝多胡/Land O Lakes 喷射低脂鲜奶油', '热量：300 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '福来康泰 有机冷榨亚麻籽油', '热量：883 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', 'Aurora 橄榄油', '热量：800 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '幸福小农 黑豆油', '热量：891 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '欧蒂斯 初榨橄榄油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '可可汇 初榨椰子油', '热量：880 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '多美鲜 无盐黄油，又叫suki 无盐黄油', '热量：179 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '弗朗多 特级初榨橄榄油', '热量：884 大卡(每100克)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '欧丽薇兰 特级初榨橄榄油', '热量：884 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('食用油、油脂及制品\n  ', '椰汇 初榨椰子油', '热量：883 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蜂蜜，又叫石蜜、石饴、食蜜、蜜、白蜜、白沙...', '热量：321 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '白砂糖，又叫白糖、糖、砂糖、石蜜、白霜糖', '热量：400 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蜂蜜（槐花）', '热量：361 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '红糖，又叫土红糖、红糖', '热量：389 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '榨菜', '热量：33 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱油，又叫豉油、酱汁、豉汁', '热量：63 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '醋，又叫苦酒、淳酢、醯、酢', '热量：31 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '芝麻酱，又叫麻酱调料', '热量：630 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳(红)，又叫南乳、酱豆腐', '热量：153 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳(白)，又叫酱豆腐、豆腐乳', '热量：135 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '花生酱', '热量：600 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '红豆沙', '热量：244 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '辣椒酱，又叫辣椒糊', '热量：36 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '味精，又叫味素、味之素', '热量：268 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '榨菜（鱼泉牌）', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '冰糖', '热量：397 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '鸡精', '热量：195 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '番茄酱，又叫茄汁', '热量：83 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '绵白糖', '热量：396 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '食盐，又叫盐、盐巴、咸鹾', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '沙拉酱（色拉酱）', '热量：724 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '豆瓣酱，又叫蚕豆酱', '热量：181 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '豆沙', '热量：247 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '榨菜（正林牌）', '热量：63 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '甜面酱，又叫面酱、甜酱', '热量：139 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱黄瓜', '热量：26 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '千岛沙拉酱，又叫沙拉酱、沙律酱、美乃滋', '热量：475 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '雪菜，又叫雪里蕻、雪里红', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '番茄沙司', '热量：112 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '白醋', '热量：6 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '苹果酱', '热量：278 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '宫岛 橄榄菜', '热量：358 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '辣椒粉', '热量：290 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蜂蜜（油菜花）', '热量：338 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蒜蓉辣酱', '热量：96 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '胡椒粉', '热量：361 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腌雪里蕻，又叫腌雪菜', '热量：29 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '草莓酱', '热量：270 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '五香豆豉，又叫大苦、香豉、康伯', '热量：270 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '豆瓣酱(辣油)', '热量：188 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳(香辣味）', '热量：158 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '牛肉酱（阿香婆）', '热量：488 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '红豆馅', '热量：261 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '豆瓣辣酱', '热量：73 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '麻辣酱', '热量：145 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '糟豆腐乳，又叫糟乳', '热量：157 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '广乐香辣咸菜', '热量：60 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳(臭)，又叫臭豆腐、臭腐乳', '热量：132 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱油(高级)', '热量：71 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '陈醋', '热量：114 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '剁辣椒', '热量：42 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '咖喱粉', '热量：341 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '香油辣酱', '热量：67 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱花生米', '热量：367 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '生抽', '热量：20 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱油(三鲜)', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '太古 纯正方糖', '热量：400 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蒜头(甜)，又叫糖蒜', '热量：117 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '蜂蜜（硬蜜）', '热量：328 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '鱼泉榨菜（低盐）', '热量：57 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '海鲜酱（阿香婆）', '热量：492 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '面包屑', '热量：355 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '家乐浓汤宝（老母鸡汤）', '热量：171 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '葱伴侣大酱 袋装180g', '热量：139 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '喜璐 果爱草莓果酱（无糖），又叫Helio...', '热量：105 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '牛头牌 沙茶酱', '热量：757 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '黄酱，又叫大豆酱、豆酱、大酱', '热量：138 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳（白，王致和牌）[酱豆腐]', '热量：153 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '甜辣黄瓜', '热量：102 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱油(一级)', '热量：66 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '美极 酸辣汤料，又叫Maggi 酸辣汤料', '热量：323 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '什锦菜', '热量：38 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '五香粉', '热量：359 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '香醋', '热量：68 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱大头菜', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '鱼子酱，又叫鱼籽酱', '热量：201 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '鱼泉牌鲜香榨菜', '热量：74 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '家乐番茄沙司', '热量：94 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '老抽', '热量：129 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '芙蓉鲜蔬汤，又叫鲜蔬汤', '热量：388 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '花椒，又叫大椒、蜀椒、点椒', '热量：316 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '萝卜干，又叫菜脯', '热量：67 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', 'SMUCKER\'S红树莓果酱', '热量：250 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', 'TEDDIE 花生酱(颗粒)', '热量：594 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '牛肉辣瓣酱', '热量：129 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腐乳（白，石宝寨牌）[酱豆腐]', '热量：115 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱油(多味)', '热量：86 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酱蘑菇', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '酸辣紫菜汤', '热量：339 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '八宝菜，又叫如意菜', '热量：78 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腌芥菜头，又叫煮芥，煮疙瘩', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '家乐牌浓汤宝（牛肉味）', '热量：184 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '五香醋', '热量：14 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '家乐牌浓汤宝（浓滑鱼汤）', '热量：161 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '黄豆酱油', '热量：38 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '光明奶酪酱（原味）', '热量：276 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '腌韭菜花', '热量：17 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '花生酱（加巧克力）', '热量：633 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '家乐牌海鲜汤', '热量：323 大卡(每100克)');
INSERT INTO `reliang` VALUES ('调味品\n  ', '海会寺白菜豆腐乳', '热量：93 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', 'Easy Fun 意式阿拉棒', '热量：396 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', 'Easy Fun 0卡果冻（奶咖风味）', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', 'Easy Fun 0卡醉醉冻（酒酿风味）', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '和路雪 轻优蛋白质豆乳雪糕', '热量：112 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '和路雪 轻优低脂香草味雪糕', '热量：105 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '饼干', '热量：435 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蛋糕(黄蛋糕)', '热量：320 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薄荷 巧克力爆米花', '热量：556 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薄荷 坚果巧克力豆', '热量：625 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薄荷 巧克力咖啡豆', '热量：417 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薄荷 冻干草莓巧克力', '热量：526 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薄荷松仁粽子糖', '热量：406 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '巧克力，又叫朱古力', '热量：589 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '冰淇淋，又叫冰激凌、雪糕', '热量：127 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '红薯干，又叫地瓜干，甘薯干', '热量：338 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '培根汉堡（夹熏肉，奶酪，加调料酱）', '热量：311 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', 'Easy S 意式咖啡包（奶萃）', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '绿豆饼（少糖少油）', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '苏打饼干', '热量：408 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '麻花', '热量：527 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '奶油蛋糕', '热量：379 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '佳梅 真之话梅', '热量：180 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '月饼(豆沙)，又叫豆沙月饼', '热量：411 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '山楂果丹皮', '热量：326 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蛋糕，又叫蛋糕', '热量：348 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '沙琪玛蛋酥', '热量：506 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', 'Easy Fun 高蛋白夹心卷（牛奶味）', '热量：485 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '单层汉堡（单层肉饼，无调料酱）', '热量：316 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '绿豆糕', '热量：351 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '西式蛋糕', '热量：316 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '野澤 猴肉（腊梅味） ', '热量：295 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '山楂球', '热量：371 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '德芙 香浓黑巧克力', '热量：542 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '夹心酥饼', '热量：482 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '月饼(五仁)', '热量：424 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '锅巴（豆香）', '热量：528 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '锅巴（小米）', '热量：554 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薯片（烧烤味）', '热量：548 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '冰棍', '热量：47 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '板油酥饼', '热量：360 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '巧克力(维夫)，又叫朱古力威化', '热量：575 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '奶糖', '热量：407 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '曲奇饼', '热量：546 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蛋糕（巧克力）', '热量：437 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '奶油饼干', '热量：431 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '酥皮糕点', '热量：429 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '和路雪绿豆妹妹冰棍', '热量：120 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '面包条（白），又叫面包条', '热量：283 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '肯德基 薯条，又叫KFC 薯条', '热量：298 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '爆米花', '热量：387 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '桃酥', '热量：483 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '时兴隆鱿鱼丝', '热量：333 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '百乐宝 巧克力雪糕', '热量：174 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '大雪糕', '热量：74 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '饼干（苏打夹心）', '热量：463 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '好丽友 蛋黄派[注心蛋黄派]', '热量：448 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '和路雪 红豆冰棍 ', '热量：91 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '牛奶糖', '热量：435 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '太平 梳打饼干海苔口味', '热量：485 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '鸡汁味干脆面（面饼+调味料）', '热量：505 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蚕豆(炸)，又叫开花豆、胡豆、夏豆、罗汉豆', '热量：447 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '巧克力（黑），又叫黑巧克力', '热量：516 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '曲奇饼（加奶油）', '热量：526 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '酥香兰花豆', '热量：419 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '金色传奇鱿鱼丝（原味）', '热量：345 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '麦当劳 薯条', '热量：242 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '雪米饼', '热量：463 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蛋糕（水果），又叫水果蛋糕、水果裸蛋糕', '热量：347 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '酥糖', '热量：436 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '水晶糖', '热量：395 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '海苔', '热量：270 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '麦当劳 脆薯饼', '热量：308 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '维维嚼益嚼（葡萄干+花生）', '热量：411 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '达能 佳钙牛奶甜酥饼干牛奶口味，又叫Dan...', '热量：468 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '牛奶饼干', '热量：408 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '可康 果冻条（苦瓜味），又叫COCON 果...', '热量：92 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '旺旺雪饼（香辣味）', '热量：400 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '薯片（香辣味）', '热量：555 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '冰淇凌（脆皮甜筒）', '热量：158 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '饼干（咸）', '热量：496 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '月饼(枣泥)', '热量：427 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '吉百利 怡口莲，又叫 Cadbury 怡口莲', '热量：416 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '智神 阿胶蜜枣', '热量：314 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '蜜麻花', '热量：369 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '混糖糕点', '热量：455 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '冰淇凌（巧克力圣代）', '热量：173 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '思朗 纤麸高纤消化饼', '热量：473 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '韩国爆米花', '热量：430 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '乐事薯片鲜浓番茄味', '热量：530 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '月饼（奶油连芸）', '热量：361 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '花生芝麻糖', '热量：498 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '德芙 榛仁巧克力', '热量：568 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '巧克力（果仁）', '热量：511 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '鲜桃果汁糖', '热量：397 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '财记 脆香花生酥', '热量：581 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '德芙 牛奶巧克力和黑巧克力精巧装', '热量：543 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '好丽友 蛋黄派（酸奶味）', '热量：436 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '新家园 烤馍锅巴（比萨风味） 75g', '热量：400 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '棒冰', '热量：73 大卡(每100克)');
INSERT INTO `reliang` VALUES ('零食、点心、冷饮\n  ', '大白兔红豆奶糖', '热量：400 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '麦当劳 麦香鸡', '热量：283 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '油面筋，又叫面筋泡、油炸生筋', '热量：492 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '千亿朵星光 益生菌含片(酸甜芒果味)', '热量：379 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', 'Easy Fun 阿胶糕（玫瑰型）', '热量：426 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', 'Easy Fun 益生元龟苓膏', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '枸杞，又叫甘杞、贡杞、枸杞子、红耳坠、苟起...', '热量：258 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '陈皮，又叫橘皮、贵老、红皮、黄橘皮、广橘皮...', '热量：319 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '栝楼根粉，又叫栝楼粉、蒌粉、天花粉', '热量：397 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '葛根，又叫野葛、鹿霍、黄斤、鸡齐根、干葛、...', '热量：181 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士螺旋藻复合片', '热量：335 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '美国GBN进口蛋白质粉', '热量：407 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '花粉（油松），又叫松花粉', '热量：398 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士乳清蛋白粉（香草味）', '热量：395 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '菊花（干），又叫怀菊花、节华、日精、女节、...', '热量：242 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '花粉（荞麦）', '热量：353 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '纽崔莱 果蔬纤维素嚼片', '热量：488 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士玫瑰果提取物复合片', '热量：402 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蚕蛹', '热量：230 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '金日 高营养蛋白质粉', '热量：197 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（雀巢 ），又叫米粉（Nestle ）', '热量：376 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '肉桂，又叫桂皮、牡桂、桂、大桂、筒桂、辣桂、玉桂', '热量：278 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '茯苓，又叫茯苓个、茯苓皮、茯苓块、赤茯苓、...', '热量：178 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '乳儿糕', '热量：366 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', 'DHC浓缩膳食纤维粉', '热量：194 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '罗汉果，又叫假苦瓜、拉汉果、光果木鳖、', '热量：246 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（蔬菜，亨氏）', '热量：394 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '光明牌切达原味芝士片，又叫光明奶酪切达原味芝士片', '热量：299 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '薄荷(鲜)，又叫香花菜、绿薄荷、夜兰香、夜...', '热量：34 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蛇', '热量：85 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '紫苏(鲜)，又叫赤苏、白苏、苏、苏叶', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '枣仁', '热量：367 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '亨氏 牌婴儿营养米粉DHA蔬菜口味，又叫 ...', '热量：365 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '天然元 啤酒酵母复合营养片含B族维生素', '热量：120 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（高蛋白，雀巢 ），又叫米粉（高蛋白，...', '热量：409 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（高蛋白，亨氏）', '热量：375 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士谷物提取物复合片（含全家福...', '热量：210 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '婴儿营养粉', '热量：426 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '美国纤雅奇异子', '热量：536 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '婴儿奶糕', '热量：345 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '薄荷(干)，又叫蕃荷菜、南薄荷、猫儿薄荷、...', '热量：271 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '甘草，又叫生甘草、粉甘草、甘草梢、甜根子、...', '热量：280 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（胡萝卜，亨氏）', '热量：386 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '冬虫夏草，又叫虫草、冬虫草（甘肃）、夏草冬...', '热量：292 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '营养乳儿糕', '热量：365 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士牡蛎提取物软胶囊（含钙）', '热量：326 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（猪肝蔬菜，亨氏）', '热量：391 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '优莎娜纤维素（水蜜桃芒果）', '热量：267 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '鸡肝蔬菜泥（亨氏）', '热量：76 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（鱼肉蔬菜，亨氏）', '热量：383 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '白芷，又叫芳香、泽芬、香白芷', '热量：324 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '决明(鲜)，又叫羊明、马蹄决明、钝叶决明、...', '热量：1 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '建昌明列子', '热量：440 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蝎子', '热量：177 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（胡萝卜，雀巢 ），又叫米粉（胡萝卜，...', '热量：374 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（番茄，亨氏）', '热量：391 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '汤臣倍健蛋白混合饮料', '热量：414 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '钙质糕粉', '热量：367 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（蔬菜，雀巢）', '热量：394 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '高良姜，又叫高凉姜、很姜、蛮姜、小良姜、海良姜', '热量：255 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '米粉（苹果，雀巢 ），又叫米粉（苹果，Ne...', '热量：374 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '花椒叶（干）', '热量：236 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '健儿粉', '热量：369 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士谷物提取物复合片（B族维生素）', '热量：406 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '红花，又叫黄蓝、红蓝、红蓝花、草红花、刺红...', '热量：220 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '阿拉斯加 康力士小麦胚芽油软胶囊', '热量：588 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '莲子健儿粉', '热量：352 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蜂蛹，又叫蜂胚、蜂仔', '热量：100 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '木榧，又叫园榧', '热量：539 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '优莎娜纤维素（杏仁口味）', '热量：303 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蜂蛹（大黄蜂）', '热量：109 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '仙人掌果，又叫仙桃', '热量：25 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '紫苏', '热量：295 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '车前子(鲜)，又叫车轮菜、车前、当道、牛舌...', '热量：73 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '砂仁，又叫缩沙蜜、缩砂仁', '热量：265 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '藿香叶(鲜)，又叫兜娄婆香', '热量：89 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '蜂蛹（油蜂）', '热量：669 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '仙人掌（食用），又叫风尾??、龙舌、平虑草...', '热量：15 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '丁香，又叫公子香、子丁香、支解香、瘦香娇、...', '热量：359 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '虎杖(鲜)', '热量：5 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '莱菔子，又叫萝卜子、芦菔子', '热量：352 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '藿香', '热量：264 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '李子园 草莓牛奶', '热量：34 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '维维 无添加蔗糖豆奶粉', '热量：434 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '天美健 大豆肽蛋白粉', '热量：280 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '闽贵海蜇丝', '热量：8 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '欧普特蒙 白金蛋白粉，又叫ON 白金蛋白粉', '热量：359 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '采森 葡萄糖酸锌口服液', '热量：0 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('其它\n  ', '嘉康利 大豆蛋白质粉(香草口味)', '热量：380 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '禧贝 胡萝卜泥', '热量：38 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '自然之家 维生素C泡腾片 （甜橙味）', '热量：301 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '优信 牛乳钙咀嚼片', '热量：410 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '美国克尔 啤酒酵母营养片', '热量：170 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '汤臣倍健 多种维生素矿物质片（女士型）', '热量：0 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '斯俪魅替餐棒（草莓白巧克力味）', '热量：369 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', 'Rafferty\'s Garden 巧克力蛋奶冻', '热量：101 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '新食力 有机速食面（胡萝卜口味）', '热量：372 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '雅培金装喜康宝星婴儿配方奶粉智护100', '热量：503 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '科力福 秋梨膏', '热量：131 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '港铧 泡椒臭干子', '热量：409 大卡(每100克)');
INSERT INTO `reliang` VALUES ('其它\n  ', '嘉力缘 黑豆醋参片【清畅】', '热量：388 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '牛肉面，又叫兰州拉面、牛腩面、牛肉拌面', '热量：127 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒上海青，又叫炒青菜', '热量：53 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '番茄炒蛋，又叫番茄炒鸡蛋、西红柿炒蛋、西红...', '热量：85 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '吐司面包，又叫吐司、白吐司、面包片、切片面包', '热量：278 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '鸡蛋羹，又叫蒸蛋', '热量：62 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '绿豆汤', '热量：46 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '素炒小白菜，又叫小青菜', '热量：46 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烧茄子', '热量：74 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '绿豆粥，又叫绿豆稀饭', '热量：48 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '香菇青菜包，又叫香菇菜包、菜包子、素包子、...', '热量：160 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蛋炒饭，又叫黄金炒饭、蛋炒饭', '热量：143 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧鳓鱼', '热量：216 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '盐水虾，又叫焖鲜虾', '热量：92 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒绿豆芽，又叫有机活体豆苗', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '葱油饼，又叫葱花饼、葱油饼', '热量：259 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清炒西葫芦，又叫炒西葫、西葫芦丝', '热量：47 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '西红柿鸡蛋面，又叫番茄蛋面', '热量：98 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '酸辣土豆丝', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧肉', '热量：522 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '韭菜包子', '热量：171 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '卤蛋，又叫卤鸡蛋', '热量：148 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清炒土豆丝', '热量：95 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清爽西兰花', '热量：63 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烧麦，又叫烧卖、糯米烧卖', '热量：220 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒大白菜，又叫大白菜', '热量：53 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '西红柿鸡蛋汤，又叫西红柿蛋汤', '热量：32 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '大饼，又叫饼，家常饼，死面饼', '热量：215 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清蒸鱼，又叫清蒸鱼、蒸鱼、鱼、蒸洄鱼', '热量：105 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '酸菜鱼，又叫酸汤鱼、酸辣鱼', '热量：98 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '寿司 自制1，又叫寿司卷', '热量：141 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '麻婆豆腐，又叫麻婆豆腐', '热量：126 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烧包菜丝', '热量：48 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '酸辣粉', '热量：98 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '青椒炒鸡蛋', '热量：105 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '素炒芹菜，又叫马家沟芹菜', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '粽子', '热量：195 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '椒油拌海带', '热量：68 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烙玉米饼，又叫玉米饼', '热量：150 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蔬菜沙拉，又叫沙拉、蔬菜', '热量：40 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清炒卷心菜，又叫炒卷心菜、卷心菜', '热量：44 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蒜味烧茄子', '热量：60 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧大排', '热量：248 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '杂粮煎饼，又叫山东杂粮煎饼', '热量：266 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '玉米小米粥，又叫玉米小米粥', '热量：47 大卡(每100毫升)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '肉松面包', '热量：326 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '豆沙包', '热量：319 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '麻酱拌黄瓜', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '凉拌黄瓜，又叫拍黄瓜、拌青瓜、拌黄瓜', '热量：46 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧带鱼', '热量：170 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '虾仁冬瓜丝', '热量：45 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '珍珠奶茶，又叫奶茶、招牌奶茶', '热量：52 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧鸡块，又叫鸡块、红烧鸡肉', '热量：224 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红卤鸡爪', '热量：236 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '扬州炒饭', '热量：146 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蛋挞，又叫蛋挞、原味蛋挞', '热量：375 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒土豆丝', '热量：115 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '牛肉包子', '热量：216 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒面/炒粉，又叫炒面、炒粉', '热量：194 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '韭菜炒绿豆芽', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '千层饼，又叫瓤子饼', '热量：269 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '菜煎饼', '热量：151 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒胡萝卜片，又叫胡萝卜', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清炒油麦菜', '热量：45 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧豆腐，又叫自磨豆腐', '热量：103 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧茄子', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蒜茸海带', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烧花菜', '热量：70 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '黄瓜炒蛋', '热量：51 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '清蒸蛋羹', '热量：61 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炒豇豆，又叫长豆角', '热量：41 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '咖喱鸡块土豆', '热量：102 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '素炒菜花', '热量：58 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '肉片炒花菜，又叫花菜炒肉、菜花炒肉', '热量：62 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '韭菜炒鸡蛋，又叫韭菜鸡蛋', '热量：94 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '茶叶蛋，又叫茶叶蛋', '热量：152 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '丝瓜炒蛋', '热量：107 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '肉丝茭白', '热量：90 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '虾仁蒸肠粉', '热量：128 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '肉片炒青椒，又叫肉炒青椒、青椒肉片', '热量：93 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '五香鸭肉', '热量：262 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '土豆烧肉', '热量：173 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '辣椒清炒苦瓜', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '炸花生米，又叫花生米', '热量：588 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '洋白菜包子', '热量：155 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '寿司 自制2', '热量：105 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '鱼香茄子', '热量：81 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '核桃酥', '热量：369 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '无糖银耳汤，又叫银耳汤', '热量：10 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '蒜拌绿豆芽', '热量：39 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '凉拌海带丝', '热量：56 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '泡椒凤爪', '热量：193 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '烤鸡翅，又叫烤翅、炸鸡翅尖、翅尖', '热量：204 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '青椒炒花菜', '热量：62 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '无糖豆浆', '热量：30 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '赤豆粽子，又叫红豆粽子、红豆粽', '热量：184 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红烧鲫鱼，又叫飘香鲫鱼', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '荞麦馒头', '热量：218 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '红豆包，又叫豆沙包;豆包;粘豆包', '热量：224 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '水煮鱼片', '热量：122 大卡(每100克)');
INSERT INTO `reliang` VALUES ('菜肴\n  ', '水煮花生米', '热量：402 大卡(每100克)');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `vname` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `height` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `sex` varchar(255) DEFAULT NULL,
  `school` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('1', 'admin', 'admin', '机器人', '100', '172', '15', '男', '机器学院');
INSERT INTO `user` VALUES ('2', '18637336376', 'shao123.', '阿狸', '50', '160', '16', '女', '诱惑学院');
INSERT INTO `user` VALUES ('3', '18312144255', '123', '冒险家', '60', '170', '17', '男', '冒险学院');
